### ISSUE TITLE
reps automatic available?

### ISSUE THREAD

**Issue by netcookies** [Fertogo/Pebble-workout-timer#100]
Could u make the reps more automatic?
detail: 
   set interval between reps 
   for example:   10  push-ups , every push-ups last 2.5s,  and interval between reps 2.5s

   reps  |  action | intervals
    1           push     2.5s
    1            up        2.5s
    2           push     2.5s
    2           up         2.5s
.......
10             push     2.5s
10              up        2.5s

push(1)  -  2.5s - up(1) - 2.5s - push(2) - 2.5s - up(1) - 2.5s  ..........-2.5s - push(10) - 2.5s - up(10)  - done

it took 10x 2.5x 2 seconds for  10 push-ups.

hope u understand my  opinion~ sry for my poor  description

**Comment by Fertogo** [comment]
You can technically do this by making a bunch of moves. I do understand that this can be annoying. 
#16 should make this easier as well as well as #104
